project_name: pullquote
gitdeploy_version: "1.0.3"
type: "static"
buildkit: true

static_dir: "{{ application_dir }}/dist"
application_dir: "{{ deploy_dir }}"

# Configs below will not usually change
deploy_dir: "{{ install_root }}/{{ project_name }}"
project_repo: "git@github.com:NUKnightLab/{{ project_name }}.git"
static_service: "s3"
static_dest: "s3://{{ static_bucket }}" # static hosted site goes in root of bucket

# Configs common to all projects
application_user: apps
install_root: /home/{{ application_user }}/sites
virtualenv_root: /home/{{ application_user }}/env

# environment keys must match deployment branch names. Value is the name
# of the branch to be merged into this environment during deployment.
supported_envs:
  stg: master
  prd: stg
